name: Compilar_Canary_APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # 🚀 CORREÇÃO: Força o disparo imediato quando qualquer TAG for criada
  workflow_dispatch: # Mantém o botão manual ativo

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Codigo
        uses: actions/checkout@v4

      - name: Configurar_Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar_Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Baixar_Pacotes
        run: flutter pub get

      - name: Rodar_Testes
        run: flutter test

      - name: Compilar_Instalador
        run: flutter build apk --debug

      - name: Criar_Artefato_Disponivel
        uses: actions/upload-artifact@v4
        with:
          name: meu-canaril-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          
