name: Gerador de APK - Canaril Almirante

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Java JDK (Obrigatorio para Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurar Framework Flutter Core
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Instalar Dependencias de Alta Performance
        run: flutter pub get

      - name: Compilar Arquivo APK Profissional
        run: flutter build apk --release

      - name: Liberar Download do Instalador APK
        uses: actions/upload-artifact@v4
        with:
          name: Canaril-Almirante-Instalador
          path: build/app/outputs/flutter-apk/app-release.apk
          
