name: Compilar_Canary_APK
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_Codigo
        uses: actions/checkout@v4
      - name: Configurar_Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configurar_Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Baixar_Pacotes
        run: flutter pub get
      - name: Rodar_Testes
        run: flutter test
        
      # 🚀 PASSO 1: Cria fisicamente a estrutura de pastas nativas
      - name: Gerar_Configuracoes_Nativas_Android
        run: flutter create . --platforms=android
        
      # 🚀 PASSO 2: Aguarda as pastas carregarem e aplica a injeção do Java 8
      - name: Configurar_Java8_Desugaring_Nativo
        run: |
          sleep 5
          sed -i 's/compileOptions {/compileOptions {\n        coreLibraryDesugaringEnabled true/' android/app/build.gradle
          sed -i 's/dependencies {/dependencies {\n        coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.0.4"/' android/app/build.gradle
          
      # 🚀 PASSO 3: Realiza o fechamento e empacotamento completo do APK
      - name: Compilar_Instalador
        run: flutter build apk --debug
      - name: Criar_Artefato_Disponivel
        uses: actions/upload-artifact@v4
        with:
          name: meu-canaril-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
